### ISSUE TITLE
Create codeschool questions string

### ISSUE THREAD

**Issue by VictorDeon** [cslms/cs-server#1]
Criar modulo de questões com respostam em string

Funcionalidades:

- [x] Comparaçâo exata
- [x] Ignorar maiúsculas/minúsculas
- [x] Regex
- [x] Ignorar acentos (use o módulo unidecode)
- [x] Testes unitários

**Comment by fabiommendes** [comment]
Todo time é brasileiro, então podemos deixar a comunicação em português :)

Funcionalidades:
[ ] Comparação exata
[ ] Ignorar maiúsculas/minúsculas
[ ] Regex
[ ] Ignorar acentos (use o módulo unidecode)
[ ] Testes unitários

**Comment by VictorArnaud** [comment]
Funcionalidades:

- [ ] Comparaçâo exata
- [ ] Ignorar maiúsculas/minúsculas
- [ ] Regex
- [ ] Ignorar acentos (use o módulo unidecode)
- [ ] Testes unitários

**Comment by fabiommendes** [comment]
Fechou? Pelo que vi no código só compara ignorando maiúsculas e minúsculas. Todo o resto não funciona.

Outra obs.: coloquem sempre um docstring nas classes:

```python
# Bad:
class Foo:
    pass

# Good
class Foo:
    """
    An object that does nothing.
    """ 
```
