### ISSUE TITLE
jsonrpc issue

### ISSUE THREAD

**Issue by VictorDeon** [cslms/cs-server#2]
Error when run `python manage.py runserver`

![erro](https://cloud.githubusercontent.com/assets/14116020/24177536/0308c448-0e82-11e7-9685-23ac05022f08.png)

**Comment by fabiommendes** [comment]
Falta a biblioteca json-rpc. Já atualizei o setup.py, então deve funcionar sem problemas na versão mais nova

**Comment by VictorDeon** [comment]
Já instalei essa biblioteca, isso que to achando estranho

**Comment by VictorDeon** [comment]
Consegui, tinha errado no nome do pacote kkk vou fechar a issue
