### ISSUE TITLE
Support for continuous integration

### ISSUE THREAD

**Issue by fabiommendes** [cslms/cs-server#3]
(vamos deixar os títulos em inglês como referência para a comunidade continuamos a discussão em portugues, ok?)

Temos que configurar o settings.py para testes na integração contínua. Algumas coisas podem ser difíceis de integrar no Travis (ex. o sandbox do boxed não funciona).    

* [x] travis.yml
* [x] Análise de cobertura com o coveralls.io
* [x] Serviço de análise estática de qualidade de código.

**Comment by VictorDeon** [comment]
Da para colocar o codeclimate para análise estática de qualidade de código

**Comment by VictorArnaud** [comment]
quinta tento fazer isso

**Comment by fabiommendes** [comment]
CI:
* Travis + codecov + quantifiedcode + codeclimate
